import {
  ProposalQueueItem,
  ProposalSummaryPayload,
} from "@/application/core/@types/Proposals/Proposal";

const now = () => new Date().toISOString();

export const mockProposals: ProposalQueueItem[] = [
  {
    id: "mock-001",
    contract: "GF-2301",
    clientName: "Marcos Ribeiro",
    clientDocument: "123.456.789-00",
    dealerName: "Auto Prime Motors",
    dealerCode: "APM-019",
    operatorName: "Letícia Andrade",
    operatorSentAt: now(),
    asset: {
      brand: "Toyota",
      model: "Corolla Cross",
      version: "XRE Hybrid",
      year: 2023,
      entryValue: 45000,
      financedValue: 145000,
      installmentValue: 4290,
      termMonths: 48,
    },
    productInfo: {
      bank: "Banco Grota",
      product: "CDC Varejo",
      modality: "Pré-fixado",
    },
    currentStatus: {
      status: "analysis",
      label: "Em análise de crédito",
      analyst: "Bruno Caldas",
      updatedAt: now(),
    },
  },
  {
    id: "mock-002",
    contract: "GF-2298",
    clientName: "Patrícia Faria",
    clientDocument: "987.654.321-00",
    dealerName: "Belluno Veículos",
    dealerCode: "BEL-443",
    operatorName: "Victor Santos",
    operatorSentAt: now(),
    asset: {
      brand: "Jeep",
      model: "Compass",
      version: "Limited T270",
      year: 2022,
      entryValue: 60000,
      financedValue: 165000,
      installmentValue: 5100,
      termMonths: 60,
    },
    productInfo: {
      bank: "Banco do Brasil",
      product: "CDC Flex",
      modality: "Pós-fixado",
    },
    currentStatus: {
      status: "pre_approved",
      label: "Pré-aprovada",
      analyst: "Maiara Couto",
      updatedAt: now(),
    },
  },
  {
    id: "mock-003",
    contract: "GF-2274",
    clientName: "Rafael Siqueira",
    clientDocument: "159.753.468-22",
    dealerName: "PowerCar Multimarcas",
    dealerCode: "PWM-101",
    operatorName: "Helena Moura",
    operatorSentAt: now(),
    asset: {
      brand: "Volkswagen",
      model: "Nivus",
      version: "Highline",
      year: 2021,
      entryValue: 20000,
      financedValue: 95000,
      installmentValue: 2890,
      termMonths: 48,
    },
    productInfo: {
      bank: "Santander",
      product: "CDC Digital",
      modality: "Pré-fixado",
    },
    currentStatus: {
      status: "awaiting_input",
      label: "Aguardando documentação",
      analyst: "Equipe Operacional",
      updatedAt: now(),
    },
  },
  {
    id: "mock-004",
    contract: "GF-2259",
    clientName: "João Felippe",
    clientDocument: "258.456.789-31",
    dealerName: "Loja Ideal Auto",
    dealerCode: "IDE-777",
    operatorName: "Camila Borges",
    operatorSentAt: now(),
    asset: {
      brand: "Chevrolet",
      model: "Tracker",
      version: "Premier",
      year: 2020,
      entryValue: 15000,
      financedValue: 82000,
      installmentValue: 2495,
      termMonths: 48,
    },
    productInfo: {
      bank: "Bradesco",
      product: "CDC Plus",
      modality: "Pós-fixado",
    },
    currentStatus: {
      status: "paid",
      label: "Pagamento confirmado",
      analyst: "Equipe Financeiro",
      updatedAt: now(),
    },
  },
];

export const mockSummary: ProposalSummaryPayload = {
  overallTotal: mockProposals.length,
  myTickets: [
    { label: "Fichas na análise", value: 3, total: mockProposals.length },
    { label: "Espera Digitação", value: 1 },
    { label: "Análise", value: 1 },
    { label: "Preenchimento", value: 0 },
    { label: "Enviadas", value: mockProposals.length, total: 36 },
  ],
  statusTotals: [
    { key: "triage", label: "Pré Digitação", value: 0 },
    { key: "awaiting_input", label: "Pendente", value: 1 },
    { key: "analysis", label: "Em Análise", value: 1 },
    { key: "filling", label: "Preenchimento", value: 0 },
    
    { key: "pre_approved", label: "Pré-Aprovada", value: 1 },
    { key: "rejected", label: "Recusada", value: 0 },
    { key: "awaiting_payment", label: "Pré Pagamento", value: 0 },
    { key: "paid", label: "Pago", value: 1 },
  ],
};
