// src/app/layout.tsx (Example for App Router)

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WhatsappGrota from "@/src/presentation/components/whatsapp/GrotaWhatsapp";
import CookieProvider from "@/src/presentation/components/providers/CookieProvider";

const inter = Inter({ subsets: ["latin"] }); 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The New Relic loader script as a string
const newRelicLoader = `
;window.NREUM||(NREUM={});NREUM.init={distributed_tracing:{enabled:true},performance:{capture_measures:true},privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]}};
;NREUM.loader_config={accountID:"7241159",trustKey:"7241159",agentID:"1134630939",licenseKey:"NRJS-92b23d5e70ac90dc2d6",applicationID:"1134630939"};
;NREUM.info={beacon:"bam.nr-data.net",errorBeacon:"bam.nr-data.net",licenseKey:"NRJS-92b23d5e70ac90dc2d6",applicationID:"1134630939",sa:1};
/*! For license information please see nr-loader-spa-1.299.0.min.js.LICENSE.txt */
(()=>{"use strict";var e,t,r={...};
// ... rest of the minified New Relic loader ...
)();
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{ __html: newRelicLoader }}
        />
      </head>
      <body className={inter.className}>
        <CookieProvider>
          {children}
          <WhatsappGrota />
        </CookieProvider>
      </body>
    </html>
  );
}