import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WhatsappGrota from "@/src/presentation/components/whatsapp/GrotaWhatsapp";
import CookieProvider from "@/src/presentation/components/providers/CookieProvider";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Grota Financiamentos de Veículos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.variable} antialiased min-h-screen flex flex-col`}>
        <CookieProvider>
          <WhatsappGrota />
          {children}
        </CookieProvider>
      </body>
    </html>
  );
}
